#!/bin/bash

LIBFT_PATH=libft/

make -C $LIBFT_PATH re
ls $LIBFT_PATH*.c > cccc
ls $LIBFT_PATH*.o > oooo
sed -i -e 's/\.o//g' oooo
sed -i -e 's/\.c//g' cccc
rm -r cccc-e oooo-e
#sed -e -i.bak 's/\.o//g' oooo
#sed -e -i.bak 's/\.c//g' cccc
diff cccc oooo
make -C $LIBFT_PATH fclean
rm -r oooo cccc
