#!/bin/bash

EXECUTABLE=gnl_exe
DIFF_FILE=diff_txt
FLAGS="-Wall -Werror -Wextra -g"
CC=gcc
INCLUDE_PATH=libft/includes
TEXT_TO_COMPARE=text.txt


echo -e "\033[32m[Test Makefile]\033[0m"
make -C libft/ fclean && make -C libft/ && $CC $FLAGS -I $INCLUDE_PATH -c get_next_line.c
echo -e "\033[32m[Compilation du programme]\033[0m"
$CC $FLAGS -I $INCLUDE_PATH -c main.c && $CC -o $EXECUTABLE get_next_line.o main.o -L libft/ -lft
echo -e "\033[32m[Lancement du programme]\n[Sauvegarde de l'execution dans \"diff.txt\"]\n[Affichage du temps d'execution]\033[0m"
time ./$EXECUTABLE>$DIFF_FILE
echo -e "\033[32m[Nombre de ligne du fichier]\033[0m"
wc -l $TEXT_TO_COMPARE | sed 's/'$TEXT_TO_COMPARE'//g' | sed 's/ //g'
echo -e "\033[32m[Supprime tous les \".o\"]\033[0m"
make -C libft/ clean
rm -r main.o get_next_line.o
echo -e "\033[32m[Test diff (ne doit rien afficher)]\033[0m" 
diff $DIFF_FILE $TEXT_TO_COMPARE
